---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  bastion_ssh_public_key_path: "%{cwd}/config/secrets/bastion/ssh.public"
  bastion_allow_cidrs:
    - "0.0.0.0/0"
  bastion_egress_cidrs:
    - "10.0.0.0/16"
  bastion_associate_public_ip_address: true

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  region: "%{hiera('bastion_state_bucket_region')}"
  bucket: "%{hiera('bastion_state_bucket_name')}"
  encrypt: "%{hiera('bastion_state_bucket_is_encrypted')}"
  key: "%{hiera('bastion_state_key')}"
