---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"
  private_network_cidr: "10.0.0.0/8"

  database_instance_type: "db.t3.micro"
  database_version: "11.13"
  database_name: "%{hiera('database_name')}"
  database_master_user: "%{hiera('database_master_user')}"
  database_master_user_password: "%{hiera('database_master_user_password')}"

  allocated_storage: 16
  use_encrypted_storage: "yes"
  use_multiple_availability_zones: "yes"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"

backend_config:
  region: "%{hiera('database_state_bucket_region')}"
  bucket: "%{hiera('database_state_bucket_name')}"
  encrypt: "%{hiera('database_state_bucket_is_encrypted')}"
  key: "%{hiera('database_state_key')}"
