---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  service_desired_count: 1

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  vault_image: "infrablocks/vault-aws:0.1.0-rc.11"
  vault_service_container_port: "8200"
  vault_service_host_port: "8200"
  vault_allow_cidrs:
    - "0.0.0.0/0"

  database_name: "%{hiera('database_name')}"
  database_master_user: "%{hiera('database_master_user')}"
  database_master_user_password: "%{hiera('database_master_user_password')}"

  database_state_bucket_name: "%{hiera('database_state_bucket_name')}"
  database_state_key: "%{hiera('database_state_key')}"
  database_state_bucket_region: "%{hiera('database_state_bucket_region')}"
  database_state_bucket_is_encrypted: "%{hiera('database_state_bucket_is_encrypted')}"

  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_is_encrypted: "%{hiera('domain_state_bucket_is_encrypted')}"
  domain_state_key: "%{hiera('domain_state_key')}"

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

  cluster_state_bucket_region: "%{hiera('cluster_state_bucket_region')}"
  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_bucket_is_encrypted: "%{hiera('cluster_state_bucket_is_encrypted')}"
  cluster_state_key: "%{hiera('cluster_state_key')}"

backend_config:
  region: "%{hiera('service_state_bucket_region')}"
  bucket: "%{hiera('service_state_bucket_name')}"
  encrypt: "%{hiera('service_state_bucket_is_encrypted')}"
  key: "%{hiera('service_state_key')}"
